# Generated by Django 3.1.13 on 2023-04-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230418_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='profilepicture',
            field=models.ImageField(upload_to=''),
        ),
    ]
